FROM ruby:2.6-alpine
ENV APP_HOME /app
RUN mkdir $APP_HOME
ADD . $APP_HOME
WORKDIR $APP_HOME
RUN apk --no-cache --update add build-base && \
gem install bundler&& \
bundle install && \
apk del build-base
ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292
CMD ["puma"]
