web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: '193.32.219.35'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://193.32.219.35/'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
